apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-middleware
spec:
  headers:
    accessControlAllowOriginList:
      - "*"
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    accessControlAllowHeaders:
      - "*"
    accessControlExposeHeaders:
      - "X-Forwarded-Role"
      - "X-Forwarded-User"
    accessControlAllowCredentials: false
    accessControlMaxAge: 100
    addVaryHeader: true