apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: read-job-api-rule
spec:
  entryPoints:
    - myapi
  routes:
    - match: "PathPrefix(`/jobRead`)"
      kind: Rule
      middlewares:
        - name: cors-middleware
        # - name: auth  # Your auth middleware
      services:
        - name: job-read-api-service
          port: http