apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-application-deployment
  labels:
    app: job-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-application
  template:
    metadata:
      labels:
        app: job-application
    spec:
      containers:
      - name: job-application
        image: veljkoskrbic/hirely-job-application-api:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5004
        env:

        - name: DB_PASS_JOB_APPLICATION
          valueFrom:
            secretKeyRef:
              name: db-job-application-mysql
              key: mysql-root-password

        - name: DB_URI_JOB_APPLICATION
          value: "mysql://root:$(DB_PASS_JOB_APPLICATION)@db-job-application-mysql.default.svc.cluster.local/my_database"

        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: rmq-rabbitmq
              key: rabbitmq-password
        
        - name: RABBITMQ_URI
          value: "amqp://admin:$(RABBIT_PASS)@rmq-rabbitmq.default.svc.cluster.local/"
        # - name: API_URL
        #   value: "http://traefik.traefik.svc.cluster.local:5000"