apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-write-db-deployment
  labels:
    app: job-write-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-write-db
  template:
    metadata:
      labels:
        app: job-write-db
    spec:
      containers:
      - name: job-write-db
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: job-write-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          value: job-read
        readinessProbe:
          exec:
            command:
              - mysqladmin 
              - ping 
              - "-h"
              - localhost 
              - "-P" 
              - "3306" 
              - "-u"
              - root
              - "--password=mysqlpassword"
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: job-write-db-service
spec:
  selector:
    app: job-write-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

