apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: veljkoskrbic/hirely-users-api:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5002
        env:

        - name: DB_PASS_USERS
          valueFrom:
            secretKeyRef:
              name: db-users-mysql
              key: mysql-root-password

        - name: DB_URI_USERS
          value: "mysql://root:$(DB_PASS_USERS)@db-users-mysql.default.svc.cluster.local/my_database"
          # mysql.connect(process.ENV.DB_URI)

        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: rmq-rabbitmq
              key: rabbitmq-password
        
        - name: RABBITMQ_URI
          value: "amqp://user:$(RABBIT_PASS)@rmq-rabbitmq.default.svc.cluster.local/"
          # rabbitmq.connect(process.ENV.RABBITMQ_URI)
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom: 
        #     secretKeyRef:
        #       name: job-read-secret
        #       key: mysql-password

        # - name: DB_URL
        #   valueFrom:
        #     configMapKeyRef:
        #       name: job-read-config
        #       key: mysql-url