apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: users-api-rule
spec:
  entryPoints:
    - myapi
  routes:
    - match: PathPrefix(`/users`)
      kind: Rule
      middlewares:
        - name: cors-middleware
        - name: auth
        # - name: pass-headers
      services:
        - name: users-api-service
          port: http
