apiVersion: v1
kind: Secret
metadata:
  name: auth0-credentials
type: Opaque
data:
  client-id: aURxa0hIZ3doRXhqcXZBZ09Da1NaV1BuNmJPZUl4OG0=
  client-secret: Mkx2ZklWRHJHdVZNaDc3dEE1UG41NldHRFlBZ3pKNWJPNVcyRVlhRDN5NlRCa3RoakJTUDFfNk1nTlJZVTZvTg==